In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas()

C:\Users\riori\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\riori\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\riori\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [3]:
pd.set_option('display.max_columns',0)
pd.set_option('display.max_colwidth',0)

In [4]:
match_lvl_data = pd.read_csv('match_level_scorecard.csv')
batsman_lvl_data = pd.read_csv('batsman_level_scorecard.csv')
bowler_lvl_data = pd.read_csv('bowler_level_scorecard.csv')
df_train = pd.read_csv('train_data_trial_2.csv')
test_data = pd.read_csv('test_data_with_samplefeatures.csv')

In [5]:
df_train['winner_01'] = df_train.apply(lambda x: 0 if (x['team1']==x['winner']) else 1, axis=1)

In [6]:
from sklearn.model_selection import train_test_split
import xgboost as xgb

In [7]:
label = df_train['winner_01']

In [8]:
label

0      1
1      0
2      0
3      0
4      1
      ..
943    0
944    1
945    1
946    1
947    1
Name: winner_01, Length: 948, dtype: int64

In [9]:
df_train.head()

   match id     team1  team1_id  ... runs_consistency strike_rate_consistency  boundary_percentage
0  9331181   Ba        11283     ...  0.937386         0.890493                1.039725
1  8797060   Ed        20        ...  0.985868         0.841438                0.968076
2  9433269   We        10576     ...  1.043717         0.668827                0.980600
3  9587073   Ga An Ws  36084     ...  1.198114         0.989524                0.995573
4  9516457   Pb Ks     30407     ...  0.860648         1.349231                0.992196

[5 rows x 37 columns]

In [19]:
df_train['team1'].unique()

array([  6,  35, 135,  39,  96,  59,   0,  54,  49,  52,  75,  58,  64,
       141, 103, 122,   5,  36, 102,  23,  93,  26,  84,  12,   1,  63,
        79,  38,  51,  77, 123,  66,  90,  99,  94, 131,  25, 121, 119,
        56,  28,  53,  20,  76,  87,  10, 138,  27,  37, 127, 120, 129,
        68,  62, 112, 128, 142,   7, 140,  21, 116,  45,  29,  50,  32,
        74,  81,  65,  98,  34,  78,  69,  18, 105, 134,  57,   8,  88,
        72, 115, 132,  97, 118,  70, 104,  22,  40,  47, 137, 113, 126,
        30,  14,  91,  82, 110,  80,  73,   2,  67,  13,  95,  55,   9,
       125,  41,  16, 111,  83,  85, 101, 139,  43,  60,  33,  44, 100,
       107,  61,  24,  48, 117,  71, 136,  46, 114,  19,  92,  31, 106,
       124,  42,  17,  15, 109,   3,  89, 108,  11,  86, 133,   4, 130])

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
from sklearn import preprocessing

In [22]:
le = preprocessing.LabelEncoder()
df_train['team1'] = le.fit_transform(df_train.team1.values)

In [23]:
df_train['team2'] = le.fit_transform(df_train.team2.values)

In [24]:
df_test['team2'] = le.fit_transform(df_test.team2.values)
df_test['team1'] = le.fit_transform(df_test.team1.values)

NameError: name 'df_test' is not defined

In [25]:
df_train['toss_winner'] = df_train['toss winner']

In [26]:
df_train.head()

   match id  team1  team1_id  ... strike_rate_consistency  boundary_percentage  toss_winner
0  9331181   6      11283     ...  0.890493                1.039725             Hl Ph
1  8797060   35     20        ...  0.841438                0.968076             Wt Is
2  9433269   135    10576     ...  0.668827                0.980600             Ne
3  9587073   39     36084     ...  0.989524                0.995573             Ga An Ws
4  9516457   96     30407     ...  1.349231                0.992196             Gt Ts

[5 rows x 38 columns]

In [27]:
df_train['winner'] = le.fit_transform(df_train.winner.values)

In [28]:
df_train['toss_winner'] = le.fit_transform(df_train.toss_winner.values)
# df_test['toss_winner'] = le.fit_transform(df_test.toss_winner.values)

In [29]:
df_train.head()

   match id  team1  team1_id  ... strike_rate_consistency  boundary_percentage  toss_winner
0  9331181   6      11283     ...  0.890493                1.039725             44
1  8797060   35     20        ...  0.841438                0.968076             138
2  9433269   135    10576     ...  0.668827                0.980600             81
3  9587073   39     36084     ...  0.989524                0.995573             34
4  9516457   96     30407     ...  1.349231                0.992196             40

[5 rows x 38 columns]

In [30]:
df_test['toss_winner'] = df_test['toss winner']

NameError: name 'df_test' is not defined

In [31]:
df_train['toss_decision'] = df_train['toss decision']
# df_test['toss_decision'] = df_test['toss decision']

df_train['toss_decision'] = le.fit_transform(df_train.toss_decision.values)
# df_test['toss_decision'] = le.fit_transform(df_test.toss_decision.values)

In [32]:
df_train.head()

   match id  team1  team1_id  ... boundary_percentage  toss_winner  toss_decision
0  9331181   6      11283     ...  1.039725            44           1
1  8797060   35     20        ...  0.968076            138          1
2  9433269   135    10576     ...  0.980600            81           1
3  9587073   39     36084     ...  0.995573            34           0
4  9516457   96     30407     ...  0.992196            40           1

[5 rows x 39 columns]

In [33]:
features = df_train[['team1', 'team2', 'toss_winner','toss_decision','ground_id', 'team_count_50runs_last15',
                       'team_winp_last5', 'team1only_avg_runs_last15', 'ground_avg_runs_last15','team_count_4runs_last15','team_count_6runs_last15','avg_stkrate','avg_runs','avg_balls_faced','avg_caught','avg_bowled','avg_lbw','avg_run out','avg_stumped','runs_consistency','strike_rate_consistency','boundary_percentage']]
target = df_train['winner_01']

In [34]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 948 entries, 0 to 947
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   team1                      948 non-null    int64
 1   team2                      948 non-null    int64
 2   toss_winner                948 non-null    int32
 3   toss_decision              948 non-null    int32
 4   ground_id                  948 non-null    int64
 5   team_count_50runs_last15   948 non-null    float64
 6   team_winp_last5            948 non-null    float64
 7   team1only_avg_runs_last15  927 non-null    float64
 8   ground_avg_runs_last15     895 non-null    float64
 9   team_count_4runs_last15    948 non-null    float64
 10  team_count_6runs_last15    948 non-null    float64
 11  avg_stkrate                948 non-null    float64
 12  avg_runs                   948 non-null    float64
 13  avg_balls_faced            948 non-null    float64
 14  avg_caught                 948 non-null    float64
 15  avg_bowled                 948 non-null    float64
 16  avg_lbw                    948 non-null    float64
 17  avg_run out                948 non-null    float64
 18  avg_stumped                948 non-null    float64
 19  runs_consistency           948 non-null    float64
 20  strike_rate_consistency    848 non-null    float64
 21  boundary_percentage        948 non-null    float64
dtypes: float64(17), int32(2), int64(3)
memory usage: 155.7 KB

In [50]:
# Selecting features and target for the model
# features = df_train[['team1', 'team1_id', 'team1_roster_ids', 'team2', 'team2_id', 'team2_roster_ids', 'toss winner', 'toss decision', 'venue', 'team_count_50runs_last15',
#                       'team_winp_last5', 'team1only_avg_runs_last15', 'ground_avg_runs_last15']]
# target = train_data['winner_01']

# # Convert categorical variables to dummy variables
# #features_encoded = pd.get_dummies(features)

# features_test = test_data[['team1', 'team1_id', 'team1_roster_ids', 'team2', 'team2_id', 'team2_roster_ids', 'toss winner', 'toss decision', 'venue', 'team_count_50runs_last15',
#                       'team_winp_last5', 'team1only_avg_runs_last15', 'ground_avg_runs_last15']]
# #target_test = test_data['winner_01']

# # Convert categorical variables to dummy variables
# features_encoded_test = pd.get_dummies(features_test)

In [35]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=42)

In [36]:
# Initialize and train the XGBoost model
model = xgb.XGBClassifier(objective='multi:softmax', num_class=2)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=2,
              num_parallel_tree=None, ...)

In [37]:
predictions = model.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.5578947368421052

In [66]:
predictions_test_ = model.predict(embeddings_test)

NameError: name 'embeddings_test' is not defined