In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
## Load libraries
import pandas as pd
import numpy as np

C:\Users\riori\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\riori\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\riori\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [3]:
# Display options
pd.set_option('display.max_columns',50)

In [5]:
train_data = pd.read_csv('train_data_trial_2.csv')
test_data = pd.read_csv('test_data_trial_2.csv')

In [6]:
train_data.shape
train_data.head(2)

(948, 37)

,match id,team1,team1_id,team1_roster_ids,team2,team2_id,team2_roster_ids,winner,winner_id,toss winner,toss decision,venue,city,match_dt,lighting,series_name,season,ground_id,team_count_50runs_last15,team_winp_last5,team1only_avg_runs_last15,team1_winp_team2_last15,ground_avg_runs_last15,winner_01,team_count_4runs_last15,team_count_6runs_last15,avg_stkrate,avg_runs,avg_balls_faced,avg_caught,avg_bowled,avg_lbw,avg_run out,avg_stumped,runs_consistency,strike_rate_consistency,boundary_percentage
0,9331181,Ba,11283,9373356.0:7857520.0:4232164.0:4566540.0:329940...,Hl Ph,12634,3500958.0:4231751.0:2735081.0:2035102.0:369833...,Hl Ph,12634,Hl Ph,field,Hr Ct Sm Ie,Indore,2022-10-20,day/night match,Sd Mq Ai Ty,2022/23,7398,1.666667,0.672131,139.0,100.0,157.178571,1,1.555556,1.642857,0.904734,0.791258,1.424594,2.222222,1.666667,2.000,0.333333,0.666667,0.937386,0.890493,1.039725
1,8797060,Ed,20,2089079.0:6139370.0:2076192.0:62432.0:2083409....,Wt Is,41,4690258.0:4069666.0:4230127.0:1942317.0:161392...,Ed,20,Wt Is,field,Kn Ol Bn Bs,Bridgetown,2022-01-23,day/night match,Ed tr of Wt Is,2021/22,1406,1.285714,1.952381,156.0,50.0,103.500000,0,1.248227,0.593496,0.864729,0.924091,1.033629,0.890625,1.117647,1.125,1.333333,3.500000,0.985868,0.841438,0.968076

In [7]:
test_data.shape
test_data.head(2)

(271, 34)

,match id,team1,team1_id,team1_roster_ids,team2,team2_id,team2_roster_ids,toss winner,toss decision,venue,city,match_dt,lighting,series_name,season,ground_id,team_count_50runs_last15,team_winp_last5,team1only_avg_runs_last15,team1_winp_team2_last15,ground_avg_runs_last15,team_count_4runs_last15,team_count_6runs_last15,avg_stkrate,avg_runs,avg_balls_faced,avg_caught,avg_bowled,avg_lbw,avg_run out,avg_stumped,runs_consistency,strike_rate_consistency,boundary_percentage
0,9250275,Jy,28594,7438955.0:8271969.0:8369661.0:3685247.0:259025...,Ud Ss of Aa,90,2436944.0:8117500.0:6703528.0:3010748.0:161387...,Ud Ss of Aa,field,Bo Ac Cb,Bulawayo,2022-07-11,day match,Ud Ss of Aa tr of Ze,2022,3226,0.000000,0.019608,NaN,0.00,NaN,0.166667,0.142857,0.745558,0.505515,0.126984,0.285714,1.000000,0.500,1.000000,1.000000,0.170240,0.366911,1.031621
1,9262189,Ga An Ws,36084,3715690.0:6818622.0:4069666.0:393014.0:4690188...,Ja Ts,36098,4690258.0:3761246.0:8464385.0:5742470.0:315072...,Ja Ts,field,Pe Sm Ga,Providence,2022-09-21,night match,Cn Pr Le,2022,13915,0.615385,0.344262,151.285714,66.67,153.5,0.945355,0.937984,1.062096,0.993186,0.891282,0.896104,1.090909,0.625,0.727273,1.333333,0.984319,1.190884,1.015238

In [8]:
train_data['winner_01'] = train_data.apply(lambda x: 1 if (x['team2']==x['winner']) else 0, axis=1)

In [9]:
## Toss winner to numerical - 1 if team2 wins, else 0

train_data['toss_winner_01'] = np.where(train_data['toss winner']==train_data['team2'], 1, 0)
test_data['toss_winner_01'] = np.where(test_data['toss winner']==test_data['team2'], 1, 0)

In [10]:
## Toss decision - categorical - 1 if winner bats, 0 otherwise

train_data['toss_decision_01'] = np.where(train_data['toss decision']=='bat', 1, 0)
test_data['toss_decision_01'] = np.where(test_data['toss decision']=='bat', 1, 0)

In [11]:
X,y = train_data[['toss_winner_01','toss_decision_01','team_count_50runs_last15','team_winp_last5','team1only_avg_runs_last15','team1_winp_team2_last15','ground_avg_runs_last15','team_count_4runs_last15','team_count_6runs_last15','avg_stkrate','avg_runs','avg_balls_faced','avg_caught','avg_bowled','avg_lbw','avg_run out','avg_stumped','runs_consistency','strike_rate_consistency','boundary_percentage']], train_data['winner_01']

In [12]:
X_test = test_data[X.columns.tolist()]

In [13]:
X_nans = X.isna().sum().reset_index()
X_nans[X_nans[0]!=0]

X_test_nans = X_test.isna().sum().reset_index()
X_test_nans[X_test_nans[0]!=0]

                        index    0
4   team1only_avg_runs_last15   21
6      ground_avg_runs_last15   53
18    strike_rate_consistency  100

                        index   0
4   team1only_avg_runs_last15   7
6      ground_avg_runs_last15  10
18    strike_rate_consistency  27

In [14]:
X.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

C:\Users\riori\anaconda3\lib\site-packages\pandas\core\frame.py:5176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [15]:
X_nans = X.isna().sum().reset_index()
X_nans[X_nans[0]!=0]

X_test_nans = X_test.isna().sum().reset_index()
X_test_nans[X_test_nans[0]!=0]

Empty DataFrame
Columns: [index, 0]
Index: []

Empty DataFrame
Columns: [index, 0]
Index: []

In [16]:
X['toss_winner_01'].value_counts()
X['toss_decision_01'].value_counts()
X['team_count_50runs_last15'].describe()

1    620
0    328
Name: toss_winner_01, dtype: int64

0    617
1    331
Name: toss_decision_01, dtype: int64

count    948.000000
mean       1.202602
std        1.008793
min        0.083333
25%        0.686678
50%        1.000000
75%        1.400000
max       11.000000
Name: team_count_50runs_last15, dtype: float64

In [17]:
from sklearn.ensemble import GradientBoostingClassifier

In [18]:
# user-defined parameters

algo_name = 'GradientBoostingClassifier'
is_ensemble = 'no'
n_trees = 10
depth = 2
lr = 0.1

In [19]:
clf_gbm = GradientBoostingClassifier(n_estimators = n_trees, max_depth = depth, learning_rate = lr).fit(X,y)

In [20]:
train_data['y_pred_01'] = clf_gbm.predict(X)
test_data['y_pred_01'] = clf_gbm.predict(X_test)

In [21]:
from sklearn.metrics import classification_report

In [22]:
# Train accuracy
print(classification_report(y, clf_gbm.predict(X), labels=[0,1]))

              precision    recall  f1-score   support

           0       0.60      0.69      0.64       468
           1       0.65      0.56      0.60       480

    accuracy                           0.62       948
   macro avg       0.63      0.62      0.62       948
weighted avg       0.63      0.62      0.62       948

In [23]:
train_data['win_pred_score'] = clf_gbm.predict_proba(X)[:,1]
test_data['win_pred_score'] = clf_gbm.predict_proba(X_test)[:,1]

In [24]:
train_data['win_pred_score'] = np.where( (train_data['y_pred_01']==0), (1-train_data['win_pred_score']), train_data['win_pred_score'])
test_data['win_pred_score'] = np.where( (test_data['y_pred_01']==0), (1-test_data['win_pred_score']), test_data['win_pred_score'])

In [25]:
train_data['win_pred_team_id'] = np.where( (train_data['y_pred_01']==0), (train_data['team1_id']), train_data['team2_id'])
test_data['win_pred_team_id'] = np.where( (test_data['y_pred_01']==0), (test_data['team1_id']), test_data['team2_id'])

In [31]:
df_feat_importance = pd.DataFrame({'feat_name':X.columns.tolist(), 'model_feat_imp_train':clf_gbm.feature_importances_}).sort_values(by='model_feat_imp_train', ascending=False)\
                                                                                                                        .reset_index(drop=True).head(30)
df_feat_importance

                    feat_name  model_feat_imp_train
0             avg_balls_faced              0.224054
1                 avg_stkrate              0.180038
2     team_count_6runs_last15              0.171552
3                 avg_run out              0.137758
4                     avg_lbw              0.066091
5                  avg_caught              0.057146
6             team_winp_last5              0.053028
7    team_count_50runs_last15              0.044973
8         boundary_percentage              0.028704
9                    avg_runs              0.021456
10     ground_avg_runs_last15              0.015201
11           toss_decision_01              0.000000
12    team_count_4runs_last15              0.000000
13                 avg_bowled              0.000000
14    team1_winp_team2_last15              0.000000
15  team1only_avg_runs_last15              0.000000
16                avg_stumped              0.000000
17           runs_consistency              0.000000
18    strike_rate_consistency              0.000000
19             toss_winner_01              0.000000

In [28]:
train_data['dataset_type'] = 'train'
test_data['dataset_type'] = 'r1'

In [29]:
## refactor

df_file1 = pd.concat([test_data[['match id','dataset_type','win_pred_team_id','win_pred_score',] + list(df_feat_importance['feat_name'].head(10))], \
                     train_data[['match id','dataset_type','win_pred_team_id','win_pred_score',] + list(df_feat_importance['feat_name'].head(10))]])

renaming_dict = {}
for i,col in enumerate(list(df_feat_importance['feat_name'].head(10))):
    renaming_dict[col] = f'indep_feat_id{i+1}'
df_file1.rename(columns=renaming_dict, inplace=True)

for i in range(1,11):
    if f'indep_feat_id{i}' not in df_file1.columns:
        df_file1[f'indep_feat_id{i}'] = np.nan

df_file1['train_algorithm'] = algo_name
df_file1['is_ensemble'] = is_ensemble
df_file1['train_hps_trees'] = n_trees
df_file1['train_hps_depth'] = depth
df_file1['train_hps_lr'] = lr

In [30]:
df_file1.shape
df_file1.head()

(1219, 19)

,match id,dataset_type,win_pred_team_id,win_pred_score,indep_feat_id1,indep_feat_id2,indep_feat_id3,indep_feat_id4,indep_feat_id5,indep_feat_id6,indep_feat_id7,indep_feat_id8,indep_feat_id9,indep_feat_id10,train_algorithm,is_ensemble,train_hps_trees,train_hps_depth,train_hps_lr
0,9250275,r1,90,0.678583,0.126984,0.745558,0.142857,1.000000,0.500000,0.285714,0.019608,0.000000,1.031621,0.505515,GradientBoostingClassifier,no,10,2,0.1
1,9262189,r1,36084,0.507586,0.891282,1.062096,0.937984,0.727273,0.625000,0.896104,0.344262,0.615385,1.015238,0.993186,GradientBoostingClassifier,no,10,2,0.1
2,9128776,r1,30428,0.507586,1.015487,0.957993,1.116505,1.000000,0.545455,1.016393,0.753086,0.842105,1.035631,1.049184,GradientBoostingClassifier,no,10,2,0.1
3,9586919,r1,36112,0.555360,0.819941,0.864815,0.612069,0.666667,1.285714,0.948276,1.487805,0.285714,0.968924,0.684273,GradientBoostingClassifier,no,10,2,0.1
4,9128538,r1,30414,0.554930,1.306907,1.061083,1.986667,0.727273,1.166667,1.189655,0.310330,2.375000,1.056680,1.147404,GradientBoostingClassifier,no,10,2,0.1

In [48]:
feature_desc = {
    'team_count_50runs_last15':'Ratio of number of 50s by players in team1 to number of 50s by players in team2 in last 15 games',
    'team_winp_last5':'Ratio of team1\'s win % to team2\'s win % in last 5 games',
    'ground_avg_runs_last15':'average runs scored in the ground in last 15 games',
    'team1_winp_team2_last15':'Team1\'s win percentage against Team2 in last 15 games',
    'team1only_avg_runs_last15':'team1\'s avg inning runs in last 15 games',
    'season_num' : 'Numerical form of season. Takes 1 for oldest season and increases for latest seasons.',
    'toss_winner_01' : 'Toss winner to numerical - 1 if team2 wins, else 0',
    'toss_decision_01' : 'Toss decision - categorical - 1 if winner bats, 0 otherwise',
    'team_count_4runs_last15': 'Ratio of total number of 4s by players in team1 to team2 in last 15 games',
    'team_count_6runs_last15': 'Ratio of total number of 6s by players in team1 to team2 in last 15 games',
    'avg_stkrate': 'Ratio of average team strike rate of all players in team1 to team2 in last 15 games',
    'avg_runs': 'Ratio of average runs scored by all players in team1 to team2 in last 15 games',
    'avg_balls_faced': 'Ratio of total number of balls faced by players in team1 to team2 in last 15 games',
    'avg_caught': 'Ratio of total number of players that were caught in team1 to team2 in last 15 games',
    'avg_bowled': 'Ratio of total number of players that were bowled in team1 to team2 in last 15 games',
    'avg_lbw': 'Ratio of total number of players that were lbw in team1 to team2 in last 15 games',
    'avg_run out': 'Ratio of total number of players that were run out in team1 to team2 in last 15 games',
    'avg_stumped': 'Ratio of total number of players that were stumped in team1 to team2 in last 15 games',
    'runs_consistency': 'Ratio of standard deviation of runs scored by players in team1 to team2 in last 15 games',
    'strike_rate_consistency': 'Ratio of standard deviation of strike rates of players in team1 to team2 in last 15 games',
    'boundary_percentage': 'Ratio of boundary percentage of players in team1 to team2 in last 15 games'
}

In [33]:
# df_feat_importance.rename(index={0:'feat_id'}, inplace=True)
df_file2 = df_feat_importance
df_file2['feat_id'] = [i+1 for i in df_file2.index]
df_file2['feat_rank_train'] = [i+1 for i in df_file2.index]
df_file2 = df_file2.set_index('feat_id')
df_file2['feat_description'] = df_file2['feat_name'].map(feature_desc)

In [34]:
df_file2

,feat_name,model_feat_imp_train,feat_rank_train,feat_description
feat_id,,,,
1,avg_balls_faced,0.224054,1,Ratio of total number of balls faced by player...
2,avg_stkrate,0.180038,2,Ratio of average team strike rate of all playe...
3,team_count_6runs_last15,0.171552,3,Ratio of total number of 6s by players in team...
4,avg_run out,0.137758,4,NaN
5,avg_lbw,0.066091,5,Ratio of total number of players that were lbw...
6,avg_caught,0.057146,6,Ratio of total number of players that were cau...
7,team_winp_last5,0.053028,7,Ratio of team1's win % to team2's win % in las...
8,team_count_50runs_last15,0.044973,8,Ratio of number of 50s by players in team1 to ...
9,boundary_percentage,0.028704,9,Ratio of boundary percentage of players in tea...
10,avg_runs,0.021456,10,Ratio of average runs scored by all players in...
11,ground_avg_runs_last15,0.015201,11,average runs scored in the ground in last 15 g...
12,toss_decision_01,0.000000,12,Toss decision - categorical - 1 if winner bats...
13,team_count_4runs_last15,0.000000,13,Ratio of total number of 4s by players in team...
14,avg_bowled,0.000000,14,Ratio of total number of players that were bow...
15,team1_winp_team2_last15,0.000000,15,Team1's win percentage against Team2 in last 1...
16,team1only_avg_runs_last15,0.000000,16,team1's avg inning runs in last 15 games
17,avg_stumped,0.000000,17,Ratio of total number of players that were stu...
18,runs_consistency,0.000000,18,Ratio of standard deviation of runs scored by ...
19,strike_rate_consistency,0.000000,19,Ratio of standard deviation of strike rates of...
20,toss_winner_01,0.000000,20,"Toss winner to numerical - 1 if team2 wins, el..."

In [35]:
df_file1.to_csv('file1.csv', index=False)
df_file2.to_csv('file2.csv')

In [36]:
import xgboost as xgb
from sklearn.metrics import classification_report

# user-defined parameters
algo_name = 'XGBoost'
is_ensemble = 'no'
n_trees = 10
depth = 2
lr = 0.1

# Preparing the model with user-defined parameters
clf_xgb = xgb.XGBClassifier(n_estimators=n_trees, max_depth=depth, learning_rate=lr, use_label_encoder=False, eval_metric='logloss').fit(X, y)

# Predicting on training data
train_data['y_pred_01'] = clf_xgb.predict(X)

# Predicting on test data
test_data['y_pred_01'] = clf_xgb.predict(X_test)

# Printing the classification report
print(classification_report(y, clf_xgb.predict(X), labels=[0, 1]))

              precision    recall  f1-score   support

           0       0.60      0.69      0.64       468
           1       0.65      0.54      0.59       480

    accuracy                           0.62       948
   macro avg       0.62      0.62      0.62       948
weighted avg       0.62      0.62      0.62       948

In [37]:
train_data['win_pred_score'] = clf_xgb.predict_proba(X)[:,1]
test_data['win_pred_score'] = clf_xgb.predict_proba(X_test)[:,1]

In [38]:
train_data['win_pred_score'] = np.where( (train_data['y_pred_01']==0), (1-train_data['win_pred_score']), train_data['win_pred_score'])
test_data['win_pred_score'] = np.where( (test_data['y_pred_01']==0), (1-test_data['win_pred_score']), test_data['win_pred_score'])

In [39]:
train_data['win_pred_team_id'] = np.where( (train_data['y_pred_01']==0), (train_data['team1_id']), train_data['team2_id'])
test_data['win_pred_team_id'] = np.where( (test_data['y_pred_01']==0), (test_data['team1_id']), test_data['team2_id'])

In [40]:
df_feat_importance = pd.DataFrame({'feat_name':X.columns.tolist(), 'model_feat_imp_train':clf_xgb.feature_importances_}).sort_values(by='model_feat_imp_train', ascending=False)\
                                                                                                                        .reset_index(drop=True).head(30)
df_feat_importance

                    feat_name  model_feat_imp_train
0             avg_balls_faced              0.187392
1     team_count_6runs_last15              0.172447
2             team_winp_last5              0.119610
3    team_count_50runs_last15              0.117843
4                  avg_caught              0.103577
5                 avg_run out              0.091953
6                 avg_stkrate              0.078230
7                     avg_lbw              0.073761
8                  avg_bowled              0.055188
9              toss_winner_01              0.000000
10    strike_rate_consistency              0.000000
11           runs_consistency              0.000000
12                avg_stumped              0.000000
13                   avg_runs              0.000000
14           toss_decision_01              0.000000
15    team_count_4runs_last15              0.000000
16     ground_avg_runs_last15              0.000000
17    team1_winp_team2_last15              0.000000
18  team1only_avg_runs_last15              0.000000
19        boundary_percentage              0.000000

In [41]:
train_data['dataset_type'] = 'train'
test_data['dataset_type'] = 'r1'

In [42]:
## refactor

df_file1 = pd.concat([test_data[['match id','dataset_type','win_pred_team_id','win_pred_score',] + list(df_feat_importance['feat_name'].head(10))], \
                     train_data[['match id','dataset_type','win_pred_team_id','win_pred_score',] + list(df_feat_importance['feat_name'].head(10))]])

renaming_dict = {}
for i,col in enumerate(list(df_feat_importance['feat_name'].head(10))):
    renaming_dict[col] = f'indep_feat_id{i+1}'
df_file1.rename(columns=renaming_dict, inplace=True)

for i in range(1,11):
    if f'indep_feat_id{i}' not in df_file1.columns:
        df_file1[f'indep_feat_id{i}'] = np.nan

df_file1['train_algorithm'] = algo_name
df_file1['is_ensemble'] = is_ensemble
df_file1['train_hps_trees'] = n_trees
df_file1['train_hps_depth'] = depth
df_file1['train_hps_lr'] = lr

In [43]:
df_file1.shape
df_file1.head()

(1219, 19)

,match id,dataset_type,win_pred_team_id,win_pred_score,indep_feat_id1,indep_feat_id2,indep_feat_id3,indep_feat_id4,indep_feat_id5,indep_feat_id6,indep_feat_id7,indep_feat_id8,indep_feat_id9,indep_feat_id10,train_algorithm,is_ensemble,train_hps_trees,train_hps_depth,train_hps_lr
0,9250275,r1,90,0.683124,0.126984,0.142857,0.019608,0.000000,0.285714,1.000000,0.745558,0.500000,1.000000,1,XGBoost,no,10,2,0.1
1,9262189,r1,36084,0.503915,0.891282,0.937984,0.344262,0.615385,0.896104,0.727273,1.062096,0.625000,1.090909,1,XGBoost,no,10,2,0.1
2,9128776,r1,30428,0.503915,1.015487,1.116505,0.753086,0.842105,1.016393,1.000000,0.957993,0.545455,0.736842,0,XGBoost,no,10,2,0.1
3,9586919,r1,36112,0.565248,0.819941,0.612069,1.487805,0.285714,0.948276,0.666667,0.864815,1.285714,1.214286,1,XGBoost,no,10,2,0.1
4,9128538,r1,30414,0.549123,1.306907,1.986667,0.310330,2.375000,1.189655,0.727273,1.061083,1.166667,1.454545,1,XGBoost,no,10,2,0.1

In [49]:
# df_feat_importance.rename(index={0:'feat_id'}, inplace=True)
df_file2 = df_feat_importance
df_file2['feat_id'] = [i+1 for i in df_file2.index]
df_file2['feat_rank_train'] = [i+1 for i in df_file2.index]
df_file2 = df_file2.set_index('feat_id')
df_file2['feat_description'] = df_file2['feat_name'].map(feature_desc)

In [50]:
df_file2

,feat_name,model_feat_imp_train,feat_rank_train,feat_description
feat_id,,,,
1,avg_balls_faced,0.187392,1,Ratio of total number of balls faced by player...
2,team_count_6runs_last15,0.172447,2,Ratio of total number of 6s by players in team...
3,team_winp_last5,0.119610,3,Ratio of team1's win % to team2's win % in las...
4,team_count_50runs_last15,0.117843,4,Ratio of number of 50s by players in team1 to ...
5,avg_caught,0.103577,5,Ratio of total number of players that were cau...
6,avg_run out,0.091953,6,Ratio of total number of players that were run...
7,avg_stkrate,0.078230,7,Ratio of average team strike rate of all playe...
8,avg_lbw,0.073761,8,Ratio of total number of players that were lbw...
9,avg_bowled,0.055188,9,Ratio of total number of players that were bow...
10,toss_winner_01,0.000000,10,"Toss winner to numerical - 1 if team2 wins, el..."
11,strike_rate_consistency,0.000000,11,Ratio of standard deviation of strike rates of...
12,runs_consistency,0.000000,12,Ratio of standard deviation of runs scored by ...
13,avg_stumped,0.000000,13,Ratio of total number of players that were stu...
14,avg_runs,0.000000,14,Ratio of average runs scored by all players in...
15,toss_decision_01,0.000000,15,Toss decision - categorical - 1 if winner bats...
16,team_count_4runs_last15,0.000000,16,Ratio of total number of 4s by players in team...
17,ground_avg_runs_last15,0.000000,17,average runs scored in the ground in last 15 g...
18,team1_winp_team2_last15,0.000000,18,Team1's win percentage against Team2 in last 1...
19,team1only_avg_runs_last15,0.000000,19,team1's avg inning runs in last 15 games
20,boundary_percentage,0.000000,20,Ratio of boundary percentage of players in tea...

In [53]:
df_file1.to_csv('file1_trial.csv', index=False)
df_file2.to_csv('file2_trial.csv')